# Generated by Django 4.2.16 on 2025-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_course_credit_remove_course_is_elective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
