# Generated by Django 4.2.16 on 2025-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_grade_user_parent_alter_parent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('High School', 'High School')], max_length=25, null=True),
        ),
    ]
