# Generated by Django 4.2.16 on 2025-11-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
